### ISSUE TITLE
Setup Help txt File

### ISSUE THREAD

**Issue by albertusgeyser** [DigiThinkIT/awesome_cart#240]
Good Day 

Could anyone add a txt file to help with setup of awesome_cart into ERPNext?

Hope there someone who can help.

Thank You
Albertus Geyser

**Comment by vjFaLk** [comment]
Hi @albertusgeyser sorry about this, but currently our app is quite dependent on other apps, some of which are still not OSS. Also, Awesome Cart isn't made in a generic way, it's been built for a particular project. This is more of a reference point for making a more generic cart in the future, something we plan to pick up at some point in time.
